import type { Metadata } from "next";
import { roboto } from "./fonts/fonts";
import "./globals.css";
import Header from "./componets/header/header";
import Footer from "./componets/footer/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${roboto.className} antialised`}>

          <Header />


          {children}


          <Footer />
      </body>
    </html>
  );
}
